# Generated by Django 4.2.7 on 2023-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_po_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic_performance',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historic_performance',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historic_performance',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historic_performance',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='quality_rating',
            field=models.FloatField(null=True),
        ),
    ]
