# Generated by Django 4.2.7 on 2023-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historic_performance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='acknowledgment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
