# Generated by Django 4.2.7 on 2023-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_po_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic_performance',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
