# Generated by Django 4.2.7 on 2023-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_historic_performance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
