# Generated by Django 4.2.7 on 2023-11-30 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_po_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 12, 44, 24, 836580, tzinfo=datetime.timezone.utc)),
        ),
    ]
