# Generated by Django 4.2.7 on 2023-11-30 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_po_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
